#pragma once

#include "standard_tools/core/value_objects.hpp"

#include <vector>

namespace standard_tools::backtest {

/// Trading instruction produced by a strategy for a specific bar.
enum class Signal {
    Hold,
    Buy,
    Sell,
};

/// Date-aligned signal generated by a strategy.
struct SignalResult {
    core::Date date;
    Signal signal = Signal::Hold;
};

}  // namespace standard_tools::backtest
